### ISSUE TITLE
Can you explain your SVM documents' function? 

### ISSUE THREAD

**Issue by masonshao** [chrisjmccormick/hog_matlab#3]
What's the function of ‘’minFunc “ and "train_svm.m" in the svm document? Can you explain it in details?
Thank you !

**Comment by chrisjmccormick** [comment]
minFunc is an optimizer for training machine learning models. 'train_svm' is for training a linear Support Vector Machine (SVM). Both of those are borrowed code, so I don't have detailed insight into them. 

You could use any machine learning library to do the training and classification.
